// example/src/components/Header.tsx
import React from 'react';
import { IonHeader, IonTitle, IonToolbar, IonBackButton, IonButtons } from '@ionic/react';

interface HeaderProps {
  title: string,
};
function Header({ title }: HeaderProps) {
  return (
    <IonHeader>
      <IonToolbar
        color="primary"
        style={{
          '--padding-top': '20px',
          '--padding-bottom': '20px',
        }}
      >
        <IonButtons slot="start">
          <IonBackButton defaultHref="/" text="" />
        </IonButtons>
        <IonTitle>{title}</IonTitle>
      </IonToolbar>
    </IonHeader>
  );
}

export default Header;

// exampleForAngular/src/app/header/header.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss'],
  exportAs: 'app-header',
})
export class HeaderComponent {

  private _title = '';

  @Input()
  set title(title: string) {
    this._title = (title && title.trim()) || '<no title set>';
  }

  get title(): string { return this._title; }

}

<ion-header>
  <ion-toolbar color="primary" style="--padding-top: 14px; --padding-bottom: 14px">
    <ion-buttons slot="start">
      <ion-back-button defaultHref="home" text=""></ion-back-button>
    </ion-buttons>
    <ion-title>{{ title }}</ion-title>
  </ion-toolbar>
</ion-header>
